/**************************************************************************
 *									  *
 *  Copyright (C)  1988 Silicon Graphics, Inc.	  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#include "flight.h"
#include "p38.h"
#define  BACKFACE TRUE		/* INCLUDES BACK LFACING POLYGONS WHEN TRUE */
/*############################################################################
 	MAKE 8 OBJECTS DEFINITION FILE 
############################################################################*/


make_p38(obj)/*	* NOTE !! EDIT 8OBJECTS for correct name */
	Object obj;
{

makeobj(obj++);		/* view[0] BELOW_LEFT_FRONT */
	color (silver9);
polf (12, right_stab_tip); 
	color (silver6);
polf (9, right_utail); 
	color (red);
RIGHT_WING_TIP;
	color (silver6);
polf (7, right_ltail); 
	color (silver9);
polf (11, right_outer_wing_top); 
polf (4, right_stab_mid); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver5);
polf (3, right_DE_right2); 
	color (silver3);
polf (3, right_DE_top); 
	color (BLUE);
polf (12, right_blue_circle1); 
polf (4, right_blue_circle3); 
	color (silver6);
polf (3, right_DE_right3); 
	color (silver4);
polf (3, right_DE_left1); 
	color (white);
polf (3, right_white_star2); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver8);
polf (3, right_DE_right5); 
	color (white);
polf (3, right_white_star3); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver6);
polf (3, right_DE_left3); 
	color (white);
polf (3, right_white_star1); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver8);
polf (3, right_DE_left5); 
	color (silver4);
polf (4, right_CD_right1); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver6);
polf (4, right_CD_right3); 
	color (silver4);
polf (4, right_CD_left1); 
polf (4, right_BC_right1); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver6);
polf (4, right_BC_right3); 
	color (silver8);
polf (4, right_CD_right5); 
	color (silver4);
polf (4, right_BC_left1); 
	color (silver6);
polf (4, right_CD_left3); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver8);
polf (4, right_CD_left5); 
	color (silver6);
polf (4, right_BC_left3); 
	color (silver8);
polf (4, right_BC_right5); 
	color (silver6);
polf (6, right_boom_front_top); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver8);
polf (4, right_BC_left5); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver6);
polf (3, fus_back_tip_right3); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver6);
polf (3, fus_back_tip_left3); 
setpattern(3);
polf (4, fus_DE_right1); 
polf (4, fus_DE_right2); 
polf (4, fus_DE_left1); 
setpattern(0);
polf (4, fus_DE_right3); 
setpattern(3);
polf (4, fus_DE_left2); 
polf (3, fus_CD_right2A); 
polf (4, fus_CD_right1); 
setpattern(0);
	color (silver5);
polf (3, fus_CD_right2B); 
	color (silver6);
polf (4, fus_CD_right3); 
setpattern(3);
polf (4, fus_CD_left1); 
setpattern(0);
polf (4, fus_DE_left3); 
setpattern(3);
polf (3, fus_CD_left2A); 
setpattern(0);
	color (silver9);
polf (4, right_inner_wing_top); 
	color (silver5);
polf (3, fus_CD_left2B); 
	color (silver9);
polf (4, left_stab_mid); 
	color (silver6);
polf (4, fus_CD_left3); 
setpattern(3);
polf (12, right_prop); 
setpattern(0);
polf (9, left_utail); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver5);
polf (4, fus_BC_right2); 
	color (silver4);
polf (4, fus_BC_right1); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver6);
polf (4, fus_BC_right3); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver4);
polf (4, fus_BC_left1); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver5);
polf (4, fus_BC_left2); 
	color (white);
LEFT_WING_TIP;
	color (silver6);
polf (4, fus_BC_left3); 
	color (silver9);
polf (4, left_inner_wing); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver4);
polf (4, fus_AB_right1); 
	color (silver6);
polf (4, fus_AB_right3); 
	color (silver4);
polf (4, fus_AB_left1); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver4);
polf (3, fus_tip_right1); 
polf (3, fus_tip_left1); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver6);
polf (3, fus_tip_left3); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (3, fus_back_tip_right5); 
polf (3, fus_back_tip_right6); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (3, fus_back_tip_left5); 
polf (3, fus_back_tip_left6); 
	color (silver7);
polf (4, fus_DE_right4); 
	color (silver8);
polf (4, fus_DE_right5); 
	color (silver6);
polf (7, left_ltail); 
	color (silver7);
polf (4, fus_CD_right4); 
polf (4, fus_DE_left4); 
	color (silver8);
polf (4, fus_DE_right6); 
polf (4, fus_DE_left5); 
polf (4, fus_DE_left6); 
polf (4, fus_CD_right5); 
	color (silver7);
polf (4, fus_CD_left4); 
	color (silver8);
polf (4, fus_CD_right6); 
	color (silver4);
polf (3, left_DE_right1); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver8);
polf (4, fus_CD_left5); 
	color (silver3);
polf (3, left_DE_top); 
	color (silver8);
polf (4, fus_CD_left6); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver9);
polf (12, left_stab_tip); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver5);
polf (3, left_DE_left2); 
	color (silver8);
polf (3, left_DE_right5); 
polf (4, fus_BC_right5); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver6);
polf (3, left_DE_left3); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver8);
polf (3, left_DE_left5); 
polf (4, fus_BC_right6); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver8);
polf (4, fus_BC_left5); 
polf (4, fus_BC_left6); 
	color (silver7);
polf (4, fus_AB_right4); 
	color (silver8);
polf (4, fus_AB_right5); 
	color (silver7);
polf (3, fus_tip_right4); 
	color (silver8);
polf (4, fus_AB_right6); 
polf (3, fus_tip_right5); 
	color (silver7);
polf (4, fus_AB_left4); 
	color (silver8);
polf (3, fus_tip_right6); 
	color (silver7);
polf (3, fus_tip_left4); 
	color (silver8);
polf (4, fus_AB_left5); 
polf (3, fus_tip_left5); 
polf (4, fus_AB_left6); 
polf (3, fus_tip_left6); 
	color (silver4);
polf (4, left_CD_right1); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver6);
polf (4, left_CD_right3); 
	color (silver4);
polf (4, left_CD_left1); 
polf (4, left_BC_right1); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver6);
polf (4, left_BC_right3); 
	color (silver8);
polf (4, left_CD_right5); 
	color (silver4);
polf (4, left_BC_left1); 
	color (silver6);
polf (4, left_CD_left3); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver8);
polf (4, left_CD_left5); 
	color (silver6);
polf (4, left_BC_left3); 
	color (silver8);
polf (4, left_BC_right5); 
	color (silver9);
polf (11, left_outer_wing); 
	color (silver6);
polf (6, left_boom_front); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver8);
polf (4, left_BC_left5); 
	color (BLUE);
polf (12, left_blue_circle); 
polf (4, left_blue_circle3); 
	color (white);
polf (3, left_white_star3); 
polf (3, left_white_star2); 
polf (3, left_white_star1); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver8);
polf (3, left_spinner_left5); 
closeobj();


makeobj(obj++);		/* view[1] BELOW_RIGHT_FRONT */
	color (silver9);
polf (12, left_stab_tip); 
	color (silver6);
polf (9, left_utail); 
polf (7, left_ltail); 
	color (silver9);
polf (11, left_outer_wing); 
polf (4, left_stab_mid); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver5);
polf (3, left_DE_left2); 
	color (silver3);
polf (3, left_DE_top); 
	color (BLUE);
polf (12, left_blue_circle); 
polf (4, left_blue_circle3); 
	color (silver6);
polf (3, left_DE_left3); 
	color (silver4);
polf (3, left_DE_right1); 
	color (white);
polf (3, left_white_star2); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver8);
polf (3, left_DE_left5); 
	color (white);
polf (3, left_white_star3); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver6);
polf (3, left_DE_right3); 
	color (white);
polf (3, left_white_star1); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver8);
polf (3, left_DE_right5); 
	color (silver4);
polf (4, left_CD_left1); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver6);
polf (4, left_CD_left3); 
	color (silver4);
polf (4, left_CD_right1); 
polf (4, left_BC_left1); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver6);
polf (4, left_BC_left3); 
	color (silver8);
polf (4, left_CD_left5); 
	color (silver4);
polf (4, left_BC_right1); 
	color (silver6);
polf (4, left_CD_right3); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver8);
polf (4, left_CD_right5); 
	color (silver6);
polf (4, left_BC_right3); 
	color (silver8);
polf (4, left_BC_left5); 
	color (silver6);
polf (6, left_boom_front); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver8);
polf (4, left_BC_right5); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver6);
polf (3, fus_back_tip_left3); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver6);
polf (3, fus_back_tip_right3); 
setpattern(3);
polf (4, fus_DE_left1); 
polf (4, fus_DE_left2); 
polf (4, fus_DE_right1); 
setpattern(0);
polf (4, fus_DE_left3); 
setpattern(3);
polf (4, fus_DE_right2); 
polf (3, fus_CD_left2A); 
polf (4, fus_CD_left1); 
setpattern(0);
	color (silver5);
polf (3, fus_CD_left2B); 
	color (silver6);
polf (4, fus_CD_left3); 
setpattern(3);
polf (4, fus_CD_right1); 
setpattern(0);
polf (4, fus_DE_right3); 
setpattern(3);
polf (3, fus_CD_right2A); 
setpattern(0);
	color (white);
LEFT_WING_TIP;
	color (silver9);
polf (4, left_inner_wing); 
	color (silver5);
polf (3, fus_CD_right2B); 
	color (silver6);
polf (4, fus_CD_right3); 
setpattern(3);
polf (12, left_prop); 
setpattern(0);
	color (silver9);
polf (4, right_stab_mid); 
	color (silver6);
polf (9, right_utail); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver5);
polf (4, fus_BC_left2); 
	color (silver4);
polf (4, fus_BC_left1); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver6);
polf (4, fus_BC_left3); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver4);
polf (4, fus_BC_right1); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver5);
polf (4, fus_BC_right2); 
	color (silver6);
polf (4, fus_BC_right3); 
	color (silver9);
polf (4, right_inner_wing_top); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver4);
polf (4, fus_AB_left1); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver4);
polf (4, fus_AB_right1); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver6);
polf (4, fus_AB_right3); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver6);
polf (3, fus_tip_left3); 
	color (silver4);
polf (3, fus_tip_left1); 
polf (3, fus_tip_right1); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (3, fus_back_tip_left5); 
polf (3, fus_back_tip_left6); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (3, fus_back_tip_right5); 
polf (3, fus_back_tip_right6); 
	color (silver7);
polf (4, fus_DE_left4); 
	color (silver8);
polf (4, fus_DE_left5); 
	color (silver6);
polf (7, right_ltail); 
	color (silver7);
polf (4, fus_CD_left4); 
polf (4, fus_DE_right4); 
	color (silver8);
polf (4, fus_DE_left6); 
polf (4, fus_DE_right5); 
polf (4, fus_DE_right6); 
polf (4, fus_CD_left5); 
	color (silver7);
polf (4, fus_CD_right4); 
	color (silver8);
polf (4, fus_CD_left6); 
	color (silver4);
polf (3, right_DE_left1); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver8);
polf (4, fus_CD_right5); 
	color (silver3);
polf (3, right_DE_top); 
	color (silver8);
polf (4, fus_CD_right6); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver9);
polf (12, right_stab_tip); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver5);
polf (3, right_DE_right2); 
	color (silver8);
polf (3, right_DE_left5); 
polf (4, fus_BC_left5); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver6);
polf (3, right_DE_right3); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver8);
polf (3, right_DE_right5); 
polf (4, fus_BC_left6); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver8);
polf (4, fus_BC_right5); 
polf (4, fus_BC_right6); 
	color (silver7);
polf (4, fus_AB_left4); 
	color (silver8);
polf (4, fus_AB_left5); 
	color (silver7);
polf (3, fus_tip_left4); 
	color (silver8);
polf (4, fus_AB_left6); 
polf (3, fus_tip_left5); 
	color (silver7);
polf (4, fus_AB_right4); 
	color (silver8);
polf (3, fus_tip_left6); 
	color (silver7);
polf (3, fus_tip_right4); 
	color (silver8);
polf (4, fus_AB_right5); 
polf (3, fus_tip_right5); 
polf (4, fus_AB_right6); 
polf (3, fus_tip_right6); 
	color (silver4);
polf (4, right_CD_left1); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver6);
polf (4, right_CD_left3); 
	color (silver4);
polf (4, right_CD_right1); 
polf (4, right_BC_left1); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver6);
polf (4, right_BC_left3); 
	color (silver8);
polf (4, right_CD_left5); 
	color (silver4);
polf (4, right_BC_right1); 
	color (silver6);
polf (4, right_CD_right3); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver8);
polf (4, right_CD_right5); 
	color (silver6);
polf (4, right_BC_right3); 
	color (silver8);
polf (4, right_BC_left5); 
	color (silver9);
polf (11, right_outer_wing_top); 
	color (silver6);
polf (6, right_boom_front_top); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver8);
polf (4, right_BC_right5); 
	color (BLUE);
polf (12, right_blue_circle1); 
polf (4, right_blue_circle3); 
	color (white);
polf (3, right_white_star3); 
	color (red);
RIGHT_WING_TIP;
	color (white);
polf (3, right_white_star2); 
polf (3, right_white_star1); 
setpattern(3);
        color (silver6);
polf (12, right_prop); 
setpattern(0);
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver7);
polf (3, right_spinner_right_4); 
closeobj();


makeobj(obj++);		/* view[2] ABOVE_LEFT_FRONT */
	color (silver3);
polf (12, right_stab_tip); 
	color (silver6);
polf (7, right_ltail); 
	color (red);
RIGHT_WING_TIP;
	color (silver6);
polf (9, right_utail); 
	color (silver3);
polf (11, right_outer_wing_top); 
	color (silver8);
polf (3, right_DE_right5); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver3);
polf (4, right_stab_mid); 
	color (silver6);
polf (3, right_DE_right3); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver8);
polf (3, right_DE_left5); 
	color (silver5);
polf (3, right_DE_right2); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver3);
polf (3, right_DE_top); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver4);
polf (3, right_DE_left1); 
	color (silver8);
polf (4, right_CD_right5); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver6);
polf (4, right_CD_right3); 
	color (silver8);
polf (4, right_CD_left5); 
polf (4, right_BC_right5); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver8);
polf (4, right_BC_left5); 
	color (silver4);
polf (4, right_CD_right1); 
	color (silver6);
polf (4, right_BC_right3); 
polf (6, right_boom_front_top); 
polf (4, right_CD_left3); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver4);
polf (4, right_BC_right1); 
polf (4, right_CD_left1); 
	color (silver6);
polf (4, right_BC_left3); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver4);
polf (4, right_BC_left1); 
	color (silver8);
polf (3, fus_back_tip_right6); 
polf (3, fus_back_tip_right5); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (3, fus_back_tip_left6); 
polf (3, fus_back_tip_left5); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (4, fus_DE_right6); 
polf (4, fus_DE_right5); 
polf (4, fus_DE_left6); 
	color (silver7);
polf (4, fus_DE_right4); 
	color (silver8);
polf (4, fus_DE_left5); 
polf (4, fus_CD_right6); 
polf (4, fus_CD_right5); 
polf (4, fus_CD_left6); 
	color (silver7);
polf (4, fus_CD_right4); 
polf (4, fus_DE_left4); 
	color (silver8);
polf (4, fus_CD_left5); 
	color (silver3);
polf (4, right_inner_wing_top); 
setpattern(3);
        color (silver6);
polf (12, right_prop); 
setpattern(0);
	color (silver7);
polf (4, fus_CD_left4); 
	color (silver8);
polf (4, fus_BC_right6); 
polf (4, fus_BC_right5); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver8);
polf (4, fus_BC_left6); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver8);
polf (4, fus_BC_left5); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver3);
polf (4, left_stab_mid); 
	color (silver6);
polf (7, left_ltail); 
	color (silver8);
polf (4, fus_AB_right6); 
polf (4, fus_AB_right5); 
	color (silver7);
polf (4, fus_AB_right4); 
	color (silver8);
polf (4, fus_AB_left6); 
	color (silver3);
polf (4, left_inner_wing); 
	color (silver8);
polf (4, fus_AB_left5); 
polf (3, fus_tip_right6); 
polf (3, fus_tip_right5); 
	color (silver7);
polf (4, fus_AB_left4); 
polf (3, fus_tip_right4); 
	color (silver8);
polf (3, fus_tip_left6); 
polf (3, fus_tip_left5); 
	color (silver7);
polf (3, fus_tip_left4); 
	color (white);
LEFT_WING_TIP;
	color (silver6);
polf (3, fus_back_tip_right3); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver6);
polf (3, fus_back_tip_left3); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver6);
polf (4, fus_DE_right3); 
setpattern(3);
polf (4, fus_DE_right2); 
setpattern(0);
polf (4, fus_CD_right3); 
polf (4, fus_DE_left3); 
setpattern(3);
polf (4, fus_DE_right1); 
polf (4, fus_DE_left2); 
polf (4, fus_DE_left1); 
setpattern(0);
	color (silver5);
polf (3, fus_CD_right2B); 
setpattern(3);
        color (silver6);
polf (3, fus_CD_right2A); 
polf (4, fus_CD_right1); 
setpattern(0);
polf (4, fus_CD_left3); 
	color (silver5);
polf (3, fus_CD_left2B); 
	color (silver6);
polf (9, left_utail); 
setpattern(3);
polf (4, fus_CD_left1); 
polf (3, fus_CD_left2A); 
setpattern(0);
polf (4, fus_BC_right3); 
	color (silver8);
polf (3, left_DE_right5); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver5);
polf (4, fus_BC_right2); 
	color (silver8);
polf (3, left_DE_left5); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver4);
polf (3, left_DE_right1); 
polf (4, fus_BC_right1); 
	color (silver6);
polf (3, left_DE_left3); 
polf (4, fus_BC_left3); 
	color (silver4);
polf (4, fus_BC_left1); 
	color (silver3);
polf (12, left_stab_tip); 
polf (3, left_DE_top); 
	color (silver5);
polf (4, fus_BC_left2); 
polf (3, left_DE_left2); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver6);
polf (4, fus_AB_right3); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver4);
polf (4, fus_AB_right1); 
	color (silver6);
polf (3, fus_tip_right3); 
polf (4, fus_AB_left3); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver4);
polf (4, fus_AB_left1); 
polf (3, fus_tip_right1); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver4);
polf (3, fus_tip_left1); 
	color (silver6);
polf (3, fus_tip_left3); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver8);
polf (4, left_CD_right5); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver6);
polf (4, left_CD_right3); 
	color (silver8);
polf (4, left_CD_left5); 
polf (4, left_BC_right5); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver8);
polf (4, left_BC_left5); 
	color (silver4);
polf (4, left_CD_right1); 
	color (silver6);
polf (4, left_BC_right3); 
polf (6, left_boom_front); 
polf (4, left_CD_left3); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver4);
polf (4, left_BC_right1); 
polf (4, left_CD_left1); 
	color (silver6);
polf (4, left_BC_left3); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver4);
polf (4, left_BC_left1); 
	color (silver3);
polf (11, left_outer_wing); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver5);
polf (3, left_spinner_left2); 
closeobj();


makeobj(obj++);		/* view[3] ABOVE_RIGHT_FRONT */
	color (silver3);
polf (12, left_stab_tip); 
	color (silver6);
polf (7, left_ltail); 
	color (silver6);
polf (9, left_utail); 
	color (silver3);
polf (11, left_outer_wing); 
	color (silver8);
polf (3, left_DE_left5); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver6);
polf (3, left_DE_left3); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver8);
polf (3, left_DE_right5); 
	color (silver3);
polf (4, left_stab_mid); 
	color (silver5);
polf (3, left_DE_left2); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver3);
polf (3, left_DE_top); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver4);
polf (3, left_DE_right1); 
	color (silver8);
polf (4, left_CD_left5); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver6);
polf (4, left_CD_left3); 
	color (silver8);
polf (4, left_CD_right5); 
polf (4, left_BC_left5); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver8);
polf (4, left_BC_right5); 
	color (silver4);
polf (4, left_CD_left1); 
	color (silver6);
polf (4, left_BC_left3); 
polf (6, left_boom_front); 
polf (4, left_CD_right3); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver4);
polf (4, left_BC_left1); 
polf (4, left_CD_right1); 
	color (silver6);
polf (4, left_BC_right3); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver4);
polf (4, left_BC_right1); 
	color (silver8);
polf (3, fus_back_tip_left6); 
polf (3, fus_back_tip_left5); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (3, fus_back_tip_right6); 
polf (3, fus_back_tip_right5); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (4, fus_DE_left6); 
polf (4, fus_DE_left5); 
polf (4, fus_DE_right6); 
	color (silver7);
polf (4, fus_DE_left4); 
	color (silver8);
polf (4, fus_DE_right5); 
polf (4, fus_CD_left6); 
polf (4, fus_CD_left5); 
polf (4, fus_CD_right6); 
	color (silver7);
polf (4, fus_CD_left4); 
polf (4, fus_DE_right4); 
	color (silver8);
polf (4, fus_CD_right5); 
	color (silver3);
polf (4, left_inner_wing); 
	color (silver7);
polf (4, fus_CD_right4); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
	color (silver8);
polf (4, fus_BC_left6); 
polf (4, fus_BC_left5); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver8);
polf (4, fus_BC_right6); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver8);
polf (4, fus_BC_right5); 
	color (silver3);
polf (4, right_stab_mid); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (white);
LEFT_WING_TIP;
	color (silver6);
polf (7, right_ltail); 
	color (silver8);
polf (4, fus_AB_left6); 
polf (4, fus_AB_left5); 
	color (silver7);
polf (4, fus_AB_left4); 
	color (silver8);
polf (4, fus_AB_right6); 
	color (silver3);
polf (4, right_inner_wing_top); 
	color (silver8);
polf (4, fus_AB_right5); 
polf (3, fus_tip_left6); 
polf (3, fus_tip_left5); 
	color (silver7);
polf (4, fus_AB_right4); 
polf (3, fus_tip_left4); 
	color (silver8);
polf (3, fus_tip_right6); 
polf (3, fus_tip_right5); 
	color (silver7);
polf (3, fus_tip_right4); 
	color (silver6);
polf (3, fus_back_tip_left3); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver6);
polf (3, fus_back_tip_right3); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver6);
polf (4, fus_DE_left3); 
setpattern(3);
polf (4, fus_DE_left2); 
setpattern(0);
polf (4, fus_CD_left3); 
polf (4, fus_DE_right3); 
setpattern(3);
polf (4, fus_DE_left1); 
polf (4, fus_DE_right2); 
polf (4, fus_DE_right1); 
setpattern(0);
	color (silver5);
polf (3, fus_CD_left2B); 
setpattern(3);
        color (silver6);
polf (3, fus_CD_left2A); 
polf (4, fus_CD_left1); 
setpattern(0);
polf (4, fus_CD_right3); 
	color (silver5);
polf (3, fus_CD_right2B); 
	color (silver6);
polf (9, right_utail); 
setpattern(3);
polf (4, fus_CD_right1); 
polf (3, fus_CD_right2A); 
setpattern(0);
polf (4, fus_BC_left3); 
	color (silver8);
polf (3, right_DE_left5); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver5);
polf (4, fus_BC_left2); 
	color (silver8);
polf (3, right_DE_right5); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver4);
polf (3, right_DE_left1); 
polf (4, fus_BC_left1); 
	color (silver6);
polf (3, right_DE_right3); 
polf (4, fus_BC_right3); 
	color (silver4);
polf (4, fus_BC_right1); 
	color (silver3);
polf (12, right_stab_tip); 
polf (3, right_DE_top); 
	color (silver5);
polf (4, fus_BC_right2); 
polf (3, right_DE_right2); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver4);
polf (4, fus_AB_left1); 
	color (silver6);
polf (3, fus_tip_left3); 
polf (4, fus_AB_right3); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver4);
polf (4, fus_AB_right1); 
polf (3, fus_tip_left1); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver4);
polf (3, fus_tip_right1); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver8);
polf (4, right_CD_left5); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver6);
polf (4, right_CD_left3); 
	color (silver8);
polf (4, right_CD_right5); 
polf (4, right_BC_left5); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver8);
polf (4, right_BC_right5); 
	color (silver4);
polf (4, right_CD_left1); 
	color (silver6);
polf (4, right_BC_left3); 
polf (6, right_boom_front_top); 
polf (4, right_CD_right3); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver4);
polf (4, right_BC_left1); 
polf (4, right_CD_right1); 
	color (silver6);
polf (4, right_BC_right3); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver4);
polf (4, right_BC_right1); 
	color (silver3);
polf (11, right_outer_wing_top); 
	color (red);
RIGHT_WING_TIP;
setpattern(3);
        color (silver6);
polf (12, right_prop); 
setpattern(0);
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver4);
polf (3, right_spinner_right1); 
closeobj();


makeobj(obj++);		/* view[4] BELOW_LEFT_BEHIND */
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver7);
polf (3, right_spinner_left4); 
setpattern(3);
        color (silver6);
polf (12, right_prop); 
setpattern(0);
	color (red);
RIGHT_WING_TIP;
	color (silver9);
polf (11, right_outer_wing_top); 
	color (silver4);
polf (4, right_BC_right1); 
	color (silver5);
polf (4, right_BC_right2); 
	color (BLUE);
polf (12, right_blue_circle1); 
polf (4, right_blue_circle3); 
	color (white);
polf (3, right_white_star1); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver6);
polf (4, right_BC_right3); 
	color (white);
polf (3, right_white_star2); 
	color (silver4);
polf (4, right_CD_right1); 
polf (4, right_BC_left1); 
	color (silver5);
polf (4, right_CD_right2); 
	color (white);
polf (3, right_white_star3); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver6);
polf (4, right_CD_right3); 
polf (6, right_boom_front_top); 
polf (4, right_BC_left3); 
	color (silver4);
polf (4, right_CD_left1); 
	color (silver8);
polf (4, right_BC_right5); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver8);
polf (4, right_BC_left5); 
polf (4, right_CD_right5); 
	color (silver6);
polf (4, right_CD_left3); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver8);
polf (4, right_CD_left5); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver4);
polf (3, fus_tip_right1); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver4);
polf (3, fus_tip_left1); 
polf (4, fus_AB_right1); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver6);
polf (4, fus_AB_right3); 
polf (3, fus_tip_left3); 
	color (silver4);
polf (4, fus_AB_left1); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver5);
polf (3, right_DE_right2); 
polf (4, fus_BC_right2); 
	color (silver3);
polf (3, right_DE_top); 
	color (silver9);
polf (12, right_stab_tip); 
	color (silver4);
polf (4, fus_BC_right1); 
	color (silver6);
polf (4, fus_BC_right3); 
polf (3, right_DE_right3); 
	color (silver4);
polf (4, fus_BC_left1); 
polf (3, right_DE_left1); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver8);
polf (3, right_DE_right5); 
	color (silver5);
polf (4, fus_BC_left2); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver8);
polf (3, right_DE_left5); 
	color (silver6);
polf (4, fus_BC_left3); 
setpattern(3);
polf (3, fus_CD_right2A); 
polf (4, fus_CD_right1); 
setpattern(0);
polf (9, right_utail); 
	color (silver5);
polf (3, fus_CD_right2B); 
	color (silver6);
polf (4, fus_CD_right3); 
setpattern(3);
polf (4, fus_CD_left1); 
polf (3, fus_CD_left2A); 
setpattern(0);
	color (silver5);
polf (3, fus_CD_left2B); 
setpattern(3);
        color (silver6);
polf (4, fus_DE_right1); 
polf (4, fus_DE_right2); 
polf (4, fus_DE_left1); 
setpattern(0);
polf (4, fus_DE_right3); 
polf (4, fus_CD_left3); 
setpattern(3);
polf (4, fus_DE_left2); 
setpattern(0);
polf (4, fus_DE_left3); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver6);
polf (3, fus_back_tip_right3); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver6);
polf (3, fus_back_tip_left3); 
	color (silver7);
polf (3, fus_tip_right4); 
	color (silver8);
polf (3, fus_tip_right5); 
polf (3, fus_tip_right6); 
	color (silver7);
polf (3, fus_tip_left4); 
polf (4, fus_AB_right4); 
	color (silver8);
polf (3, fus_tip_left5); 
polf (3, fus_tip_left6); 
polf (4, fus_AB_right5); 
	color (silver9);
polf (4, right_inner_wing_top); 
	color (silver8);
polf (4, fus_AB_right6); 
	color (silver7);
polf (4, fus_AB_left4); 
	color (silver8);
polf (4, fus_AB_left5); 
polf (4, fus_AB_left6); 
	color (silver6);
polf (7, right_ltail); 
	color (white);
LEFT_WING_TIP;
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver9);
polf (4, right_stab_mid); 
	color (silver8);
polf (4, fus_BC_right5); 
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver8);
polf (4, fus_BC_right6); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver8);
polf (4, fus_BC_left5); 
polf (4, fus_BC_left6); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
	color (silver7);
polf (4, fus_CD_right4); 
	color (silver9);
polf (4, left_inner_wing); 
	color (silver8);
polf (4, fus_CD_right5); 
	color (silver7);
polf (4, fus_DE_right4); 
polf (4, fus_CD_left4); 
	color (silver8);
polf (4, fus_CD_right6); 
polf (4, fus_CD_left5); 
polf (4, fus_CD_left6); 
polf (4, fus_DE_right5); 
	color (silver7);
polf (4, fus_DE_left4); 
	color (silver8);
polf (4, fus_DE_right6); 
polf (4, fus_DE_left5); 
polf (4, fus_DE_left6); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (3, fus_back_tip_right5); 
polf (3, fus_back_tip_right6); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (3, fus_back_tip_left5); 
polf (3, fus_back_tip_left6); 
	color (silver4);
polf (4, left_BC_right1); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver6);
polf (4, left_BC_right3); 
	color (silver4);
polf (4, left_CD_right1); 
polf (4, left_BC_left1); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver6);
polf (4, left_CD_right3); 
polf (6, left_boom_front); 
polf (4, left_BC_left3); 
	color (silver4);
polf (4, left_CD_left1); 
	color (silver8);
polf (4, left_BC_right5); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver8);
polf (4, left_BC_left5); 
polf (4, left_CD_right5); 
	color (silver6);
polf (4, left_CD_left3); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver8);
polf (4, left_CD_left5); 
	color (silver4);
polf (3, left_DE_right1); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver3);
polf (3, left_DE_top); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver5);
polf (3, left_DE_left2); 
	color (silver9);
polf (4, left_stab_mid); 
	color (silver8);
polf (3, left_DE_right5); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver6);
polf (3, left_DE_left3); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver8);
polf (3, left_DE_left5); 
	color (silver9);
polf (11, left_outer_wing); 
	color (silver6);
polf (9, left_utail); 
	color (BLUE);
polf (12, left_blue_circle); 
polf (4, left_blue_circle3); 
	color (white);
polf (3, left_white_star1); 
polf (3, left_white_star3); 
polf (3, left_white_star2); 
	color (silver6);
polf (7, left_ltail); 
	color (silver9);
polf (12, left_stab_tip); 
closeobj();


makeobj(obj++);		/* view[5] BELOW_RIGHT_BEHIND */
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver7);
polf (3, left_spinner_right_4); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
	color (silver9);
polf (11, left_outer_wing); 
	color (silver4);
polf (4, left_BC_left1); 
	color (silver5);
polf (4, left_BC_left2); 
	color (BLUE);
polf (12, left_blue_circle); 
polf (4, left_blue_circle3); 
	color (white);
polf (3, left_white_star1); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver6);
polf (4, left_BC_left3); 
	color (white);
polf (3, left_white_star2); 
	color (silver4);
polf (4, left_CD_left1); 
polf (4, left_BC_right1); 
	color (silver5);
polf (4, left_CD_left2); 
	color (white);
polf (3, left_white_star3); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver6);
polf (4, left_CD_left3); 
polf (6, left_boom_front); 
polf (4, left_BC_right3); 
	color (silver4);
polf (4, left_CD_right1); 
	color (silver8);
polf (4, left_BC_left5); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver8);
polf (4, left_BC_right5); 
polf (4, left_CD_left5); 
	color (silver6);
polf (4, left_CD_right3); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver8);
polf (4, left_CD_right5); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver6);
polf (3, fus_tip_left3); 
	color (silver4);
polf (3, fus_tip_left1); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver4);
polf (3, fus_tip_right1); 
polf (4, fus_AB_left1); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver4);
polf (4, fus_AB_right1); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver6);
polf (4, fus_AB_right3); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver5);
polf (3, left_DE_left2); 
polf (4, fus_BC_left2); 
	color (silver3);
polf (3, left_DE_top); 
	color (silver9);
polf (12, left_stab_tip); 
	color (silver4);
polf (4, fus_BC_left1); 
	color (silver6);
polf (4, fus_BC_left3); 
polf (3, left_DE_left3); 
	color (silver4);
polf (4, fus_BC_right1); 
polf (3, left_DE_right1); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver8);
polf (3, left_DE_left5); 
	color (silver5);
polf (4, fus_BC_right2); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver8);
polf (3, left_DE_right5); 
	color (silver6);
polf (4, fus_BC_right3); 
setpattern(3);
polf (3, fus_CD_left2A); 
polf (4, fus_CD_left1); 
setpattern(0);
polf (9, left_utail); 
	color (silver5);
polf (3, fus_CD_left2B); 
	color (silver6);
polf (4, fus_CD_left3); 
setpattern(3);
polf (4, fus_CD_right1); 
polf (3, fus_CD_right2A); 
polf (4, fus_DE_left1); 
setpattern(0);
	color (silver5);
polf (3, fus_CD_right2B); 
setpattern(3);
        color (silver6);
polf (4, fus_DE_left2); 
polf (4, fus_DE_right1); 
setpattern(0);
polf (4, fus_DE_left3); 
polf (4, fus_CD_right3); 
setpattern(3);
polf (4, fus_DE_right2); 
setpattern(0);
polf (4, fus_DE_right3); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver6);
polf (3, fus_back_tip_left3); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver6);
polf (3, fus_back_tip_right3); 
	color (white);
LEFT_WING_TIP;
	color (silver7);
polf (3, fus_tip_left4); 
	color (silver8);
polf (3, fus_tip_left5); 
polf (3, fus_tip_left6); 
	color (silver7);
polf (3, fus_tip_right4); 
polf (4, fus_AB_left4); 
	color (silver8);
polf (3, fus_tip_right5); 
polf (3, fus_tip_right6); 
polf (4, fus_AB_left5); 
	color (silver9);
polf (4, left_inner_wing); 
	color (silver8);
polf (4, fus_AB_left6); 
	color (silver7);
polf (4, fus_AB_right4); 
	color (silver8);
polf (4, fus_AB_right5); 
polf (4, fus_AB_right6); 
	color (silver6);
polf (7, left_ltail); 
	color (silver9);
polf (4, left_stab_mid); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver8);
polf (4, fus_BC_left5); 
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver8);
polf (4, fus_BC_left6); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver8);
polf (4, fus_BC_right5); 
polf (4, fus_BC_right6); 
setpattern(3);
        color (silver6);
polf (12, right_prop); 
setpattern(0);
	color (silver7);
polf (4, fus_CD_left4); 
	color (silver9);
polf (4, right_inner_wing_top); 
	color (silver8);
polf (4, fus_CD_left5); 
	color (silver7);
polf (4, fus_DE_left4); 
polf (4, fus_CD_right4); 
	color (silver8);
polf (4, fus_CD_left6); 
polf (4, fus_CD_right5); 
polf (4, fus_CD_right6); 
polf (4, fus_DE_left5); 
	color (silver7);
polf (4, fus_DE_right4); 
	color (silver8);
polf (4, fus_DE_left6); 
polf (4, fus_DE_right5); 
polf (4, fus_DE_right6); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (3, fus_back_tip_left5); 
polf (3, fus_back_tip_left6); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (3, fus_back_tip_right5); 
polf (3, fus_back_tip_right6); 
	color (silver4);
polf (4, right_BC_left1); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver6);
polf (4, right_BC_left3); 
	color (silver4);
polf (4, right_CD_left1); 
polf (4, right_BC_right1); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver6);
polf (4, right_CD_left3); 
polf (6, right_boom_front_top); 
polf (4, right_BC_right3); 
	color (silver4);
polf (4, right_CD_right1); 
	color (silver8);
polf (4, right_BC_left5); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver8);
polf (4, right_BC_right5); 
polf (4, right_CD_left5); 
	color (silver6);
polf (4, right_CD_right3); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver8);
polf (4, right_CD_right5); 
	color (silver4);
polf (3, right_DE_left1); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver3);
polf (3, right_DE_top); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver5);
polf (3, right_DE_right2); 
	color (silver8);
polf (3, right_DE_left5); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver6);
polf (3, right_DE_right3); 
	color (silver9);
polf (4, right_stab_mid); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver8);
polf (3, right_DE_right5); 
	color (silver9);
polf (11, right_outer_wing_top); 
	color (silver6);
polf (9, right_utail); 
	color (red);
RIGHT_WING_TIP;
	color (BLUE);
polf (12, right_blue_circle1); 
polf (4, right_blue_circle3); 
	color (white);
polf (3, right_white_star1); 
polf (3, right_white_star3); 
polf (3, right_white_star2); 
	color (silver6);
polf (7, right_ltail); 
	color (silver9);
polf (12, right_stab_tip); 
closeobj();


makeobj(obj++);		/* view[6] ABOVE_LEFT_BEHIND */
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver5);
polf (3, right_spinner_left2); 
setpattern(3);
        color (silver6);
polf (12, right_prop); 
setpattern(0);
	color (red);
RIGHT_WING_TIP;
	color (silver8);
polf (4, right_BC_right5); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver6);
polf (6, right_boom_front_top); 
	color (silver3);
polf (11, right_outer_wing_top); 
	color (silver8);
polf (4, right_BC_left5); 
	color (silver6);
polf (4, right_BC_right3); 
	color (silver8);
polf (4, right_CD_right5); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver6);
polf (4, right_CD_right3); 
	color (silver4);
polf (4, right_BC_right1); 
	color (silver8);
polf (4, right_CD_left5); 
	color (silver6);
polf (4, right_BC_left3); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver4);
polf (4, right_BC_left1); 
polf (4, right_CD_right1); 
	color (silver6);
polf (4, right_CD_left3); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver4);
polf (4, right_CD_left1); 
	color (silver8);
polf (3, fus_tip_right6); 
polf (4, fus_AB_right6); 
polf (3, fus_tip_right5); 
polf (4, fus_AB_right5); 
	color (silver7);
polf (3, fus_tip_right4); 
	color (silver8);
polf (3, fus_tip_left6); 
	color (silver7);
polf (4, fus_AB_right4); 
	color (silver8);
polf (3, fus_tip_left5); 
polf (4, fus_AB_left6); 
	color (silver7);
polf (3, fus_tip_left4); 
	color (silver8);
polf (4, fus_AB_left5); 
	color (silver7);
polf (4, fus_AB_left4); 
	color (silver8);
polf (4, fus_BC_right6); 
polf (4, fus_BC_right5); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver8);
polf (4, fus_BC_left6); 
polf (3, right_DE_right5); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver6);
polf (3, right_DE_right3); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver8);
polf (4, fus_BC_left5); 
polf (3, right_DE_left5); 
	color (silver5);
polf (3, right_DE_right2); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver3);
polf (12, right_stab_tip); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver8);
polf (4, fus_CD_right6); 
	color (silver3);
polf (3, right_DE_top); 
	color (silver8);
polf (4, fus_CD_right5); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver4);
polf (3, right_DE_left1); 
	color (silver8);
polf (4, fus_CD_left6); 
	color (silver7);
polf (4, fus_CD_right4); 
	color (silver8);
polf (4, fus_CD_left5); 
polf (4, fus_DE_right6); 
polf (4, fus_DE_right5); 
polf (4, fus_DE_left6); 
	color (silver7);
polf (4, fus_DE_right4); 
polf (4, fus_CD_left4); 
	color (silver6);
polf (7, right_ltail); 
	color (silver8);
polf (4, fus_DE_left5); 
	color (silver7);
polf (4, fus_DE_left4); 
	color (silver8);
polf (3, fus_back_tip_right6); 
polf (3, fus_back_tip_right5); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver8);
polf (3, fus_back_tip_left6); 
polf (3, fus_back_tip_left5); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver4);
polf (3, fus_tip_right1); 
polf (3, fus_tip_left1); 
	color (silver6);
polf (3, fus_tip_left3); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver6);
polf (4, fus_AB_right3); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver4);
polf (4, fus_AB_right1); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver4);
polf (4, fus_AB_left1); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver3);
polf (4, right_inner_wing_top); 
	color (silver6);
polf (4, fus_BC_right3); 
	color (silver5);
polf (4, fus_BC_right2); 
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver4);
polf (4, fus_BC_right1); 
	color (silver5);
polf (3, left_spinner_right2); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver6);
polf (4, fus_BC_left3); 
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver4);
polf (4, fus_BC_left1); 
	color (silver5);
polf (4, fus_BC_left2); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver6);
polf (9, right_utail); 
	color (silver3);
polf (4, right_stab_mid); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
polf (4, fus_CD_right3); 
	color (silver5);
polf (3, fus_CD_right2B); 
	color (silver3);
polf (4, left_inner_wing); 
	color (white);
LEFT_WING_TIP;
setpattern(3);
        color (silver6);
polf (3, fus_CD_right2A); 
setpattern(0);
polf (4, fus_DE_right3); 
setpattern(3);
polf (4, fus_CD_right1); 
setpattern(0);
polf (4, fus_CD_left3); 
	color (silver5);
polf (3, fus_CD_left2B); 
setpattern(3);
        color (silver6);
polf (4, fus_CD_left1); 
polf (3, fus_CD_left2A); 
polf (4, fus_DE_right2); 
setpattern(0);
polf (4, fus_DE_left3); 
setpattern(3);
polf (4, fus_DE_right1); 
polf (4, fus_DE_left2); 
polf (4, fus_DE_left1); 
setpattern(0);
polf (3, fus_back_tip_right3); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver6);
polf (3, fus_back_tip_left3); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver8);
polf (4, left_BC_right5); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver6);
polf (6, left_boom_front); 
	color (silver8);
polf (4, left_BC_left5); 
	color (silver6);
polf (4, left_BC_right3); 
	color (silver8);
polf (4, left_CD_right5); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver6);
polf (4, left_CD_right3); 
	color (silver4);
polf (4, left_BC_right1); 
	color (silver8);
polf (4, left_CD_left5); 
	color (silver6);
polf (4, left_BC_left3); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver4);
polf (4, left_BC_left1); 
polf (4, left_CD_right1); 
	color (silver6);
polf (4, left_CD_left3); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver4);
polf (4, left_CD_left1); 
	color (silver8);
polf (3, left_DE_right5); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver8);
polf (3, left_DE_left5); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver4);
polf (3, left_DE_right1); 
	color (silver6);
polf (3, left_DE_left3); 
	color (silver3);
polf (3, left_DE_top); 
	color (silver5);
polf (3, left_DE_left2); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver3);
polf (4, left_stab_mid); 
polf (11, left_outer_wing); 
	color (silver6);
polf (7, left_ltail); 
polf (9, left_utail); 
	color (silver3);
polf (12, left_stab_tip); 
closeobj();


makeobj(obj++);		/* view[7] ABOVE_RIGHT_BEHIND */
	color (silver7);
polf (3, left_spinner_left4); 
	color (silver8);
polf (3, left_spinner_left5); 
	color (silver6);
polf (3, left_spinner_left3); 
	color (silver9);
polf (3, left_spinner_bottom); 
	color (silver5);
polf (3, left_spinner_left2); 
	color (silver8);
polf (3, left_spinner_right5); 
	color (silver4);
polf (3, left_spinner_left1); 
	color (silver7);
polf (3, left_spinner_right_4); 
	color (silver6);
polf (3, left_spinner_right3); 
	color (silver3);
polf (3, left_spinner_top); 
	color (silver4);
polf (3, left_spinner_right1); 
	color (silver5);
polf (3, left_spinner_right2); 
setpattern(3);
        color (silver6);
polf (12, left_prop); 
setpattern(0);
	color (silver8);
polf (4, left_BC_left5); 
	color (silver7);
polf (4, left_BC_left4); 
	color (silver9);
polf (4, left_BC_bottom); 
	color (silver6);
polf (6, left_boom_front); 
	color (silver3);
polf (11, left_outer_wing); 
	color (silver8);
polf (4, left_BC_right5); 
	color (silver6);
polf (4, left_BC_left3); 
	color (silver8);
polf (4, left_CD_left5); 
	color (silver7);
polf (4, left_CD_left4); 
	color (silver9);
polf (4, left_CD_bottom); 
	color (silver5);
polf (4, left_BC_left2); 
	color (silver7);
polf (4, left_BC_right4); 
	color (silver6);
polf (4, left_CD_left3); 
	color (silver4);
polf (4, left_BC_left1); 
	color (silver8);
polf (4, left_CD_right5); 
	color (silver6);
polf (4, left_BC_right3); 
	color (silver3);
polf (4, left_BC_top); 
	color (silver5);
polf (4, left_CD_left2); 
	color (silver7);
polf (4, left_CD_right4); 
	color (silver5);
polf (4, left_BC_right2); 
	color (silver4);
polf (4, left_BC_right1); 
polf (4, left_CD_left1); 
	color (silver6);
polf (4, left_CD_right3); 
	color (silver3);
polf (4, left_CD_top); 
	color (silver5);
polf (4, left_CD_right2); 
	color (silver4);
polf (4, left_CD_right1); 
	color (silver8);
polf (3, fus_tip_left6); 
polf (4, fus_AB_left6); 
polf (3, fus_tip_left5); 
polf (4, fus_AB_left5); 
	color (silver7);
polf (3, fus_tip_left4); 
	color (silver8);
polf (3, fus_tip_right6); 
	color (silver7);
polf (4, fus_AB_left4); 
	color (silver8);
polf (3, fus_tip_right5); 
polf (4, fus_AB_right6); 
	color (silver7);
polf (3, fus_tip_right4); 
	color (silver8);
polf (4, fus_AB_right5); 
	color (silver7);
polf (4, fus_AB_right4); 
	color (silver8);
polf (4, fus_BC_left6); 
polf (4, fus_BC_left5); 
	color (silver7);
polf (4, fus_BC_left4); 
	color (silver8);
polf (4, fus_BC_right6); 
polf (3, left_DE_left5); 
	color (silver7);
polf (3, left_DE_left4); 
	color (silver6);
polf (3, left_DE_left3); 
	color (silver9);
polf (3, left_DE_bottom); 
	color (silver8);
polf (4, fus_BC_right5); 
polf (3, left_DE_right5); 
	color (silver5);
polf (3, left_DE_left2); 
	color (silver7);
polf (3, left_DE_right4); 
	color (silver4);
polf (3, left_DE_left1); 
	color (silver6);
polf (3, left_DE_right3); 
	color (silver3);
polf (12, left_stab_tip); 
	color (silver7);
polf (4, fus_BC_right4); 
	color (silver8);
polf (4, fus_CD_left6); 
	color (silver3);
polf (3, left_DE_top); 
	color (silver8);
polf (4, fus_CD_left5); 
	color (silver5);
polf (3, left_DE_right2); 
	color (silver4);
polf (3, left_DE_right1); 
	color (silver8);
polf (4, fus_CD_right6); 
	color (silver7);
polf (4, fus_CD_left4); 
	color (silver8);
polf (4, fus_CD_right5); 
polf (4, fus_DE_left6); 
polf (4, fus_DE_left5); 
polf (4, fus_DE_right6); 
	color (silver7);
polf (4, fus_DE_left4); 
polf (4, fus_CD_right4); 
	color (silver6);
polf (7, left_ltail); 
	color (silver8);
polf (4, fus_DE_right5); 
	color (silver7);
polf (4, fus_DE_right4); 
	color (silver8);
polf (3, fus_back_tip_left6); 
polf (3, fus_back_tip_left5); 
	color (silver7);
polf (3, fus_back_tip_left4); 
	color (silver8);
polf (3, fus_back_tip_right6); 
polf (3, fus_back_tip_right5); 
	color (silver7);
polf (3, fus_back_tip_right4); 
	color (silver6);
polf (3, fus_tip_left3); 
	color (silver5);
polf (3, fus_tip_left2); 
	color (silver4);
polf (3, fus_tip_left1); 
polf (3, fus_tip_right1); 
	color (silver6);
polf (3, fus_tip_right3); 
	color (silver5);
polf (3, fus_tip_right2); 
	color (silver6);
polf (4, fus_AB_left3); 
	color (silver5);
polf (4, fus_AB_left2); 
	color (silver4);
polf (4, fus_AB_left1); 
	color (silver6);
polf (4, fus_AB_right3); 
	color (silver4);
polf (4, fus_AB_right1); 
	color (silver5);
polf (4, fus_AB_right2); 
	color (silver3);
polf (4, left_inner_wing); 
	color (silver6);
polf (4, fus_BC_left3); 
	color (white);
LEFT_WING_TIP;
	color (silver5);
polf (4, fus_BC_left2); 
	color (silver7);
polf (3, right_spinner_left4); 
	color (silver8);
polf (3, right_spinner_left5); 
	color (silver6);
polf (3, right_spinner_left3); 
	color (silver9);
polf (3, right_spinner_bottom); 
	color (silver4);
polf (4, fus_BC_left1); 
	color (silver5);
polf (3, right_spinner_left2); 
	color (silver8);
polf (3, right_spinner_right5); 
	color (silver6);
polf (4, fus_BC_right3); 
	color (silver7);
polf (3, right_spinner_right_4); 
	color (silver4);
polf (3, right_spinner_left1); 
	color (silver4);
polf (4, fus_BC_right1); 
	color (silver5);
polf (4, fus_BC_right2); 
	color (silver3);
polf (3, right_spinner_top); 
	color (silver6);
polf (3, right_spinner_right3); 
	color (silver4);
polf (3, right_spinner_right1); 
	color (silver5);
polf (3, right_spinner_right2); 
	color (silver6);
polf (9, left_utail); 
setpattern(3);
polf (12, right_prop); 
setpattern(0);
polf (4, fus_CD_left3); 
	color (silver3);
polf (4, left_stab_mid); 
	color (silver5);
polf (3, fus_CD_left2B); 
	color (silver3);
polf (4, right_inner_wing_top); 
setpattern(3);
        color (silver6);
polf (3, fus_CD_left2A); 
setpattern(0);
polf (4, fus_DE_left3); 
setpattern(3);
polf (4, fus_CD_left1); 
setpattern(0);
polf (4, fus_CD_right3); 
	color (silver5);
polf (3, fus_CD_right2B); 
setpattern(3);
        color (silver6);
polf (4, fus_CD_right1); 
polf (3, fus_CD_right2A); 
polf (4, fus_DE_left2); 
setpattern(0);
polf (4, fus_DE_right3); 
setpattern(3);
polf (4, fus_DE_left1); 
polf (4, fus_DE_right2); 
polf (4, fus_DE_right1); 
setpattern(0);
polf (3, fus_back_tip_left3); 
	color (silver5);
polf (3, fus_back_tip_left2); 
	color (silver4);
polf (3, fus_back_tip_left1); 
	color (silver6);
polf (3, fus_back_tip_right3); 
	color (silver5);
polf (3, fus_back_tip_right2); 
	color (silver4);
polf (3, fus_back_tip_right1); 
	color (silver8);
polf (4, right_BC_left5); 
	color (silver7);
polf (4, right_BC_left4); 
	color (silver9);
polf (4, right_BC_bottom); 
	color (silver6);
polf (6, right_boom_front_top); 
	color (silver8);
polf (4, right_BC_right5); 
	color (silver6);
polf (4, right_BC_left3); 
	color (silver8);
polf (4, right_CD_left5); 
	color (silver7);
polf (4, right_CD_left4); 
	color (silver9);
polf (4, right_CD_bottom); 
	color (silver5);
polf (4, right_BC_left2); 
	color (silver7);
polf (4, right_BC_right4); 
	color (silver6);
polf (4, right_CD_left3); 
	color (silver4);
polf (4, right_BC_left1); 
	color (silver8);
polf (4, right_CD_right5); 
	color (silver6);
polf (4, right_BC_right3); 
	color (silver3);
polf (4, right_BC_top); 
	color (silver5);
polf (4, right_CD_left2); 
	color (silver7);
polf (4, right_CD_right4); 
	color (silver5);
polf (4, right_BC_right2); 
	color (silver4);
polf (4, right_BC_right1); 
polf (4, right_CD_left1); 
	color (silver6);
polf (4, right_CD_right3); 
	color (silver3);
polf (4, right_CD_top); 
	color (silver5);
polf (4, right_CD_right2); 
	color (silver4);
polf (4, right_CD_right1); 
	color (silver8);
polf (3, right_DE_left5); 
	color (silver7);
polf (3, right_DE_left4); 
	color (silver6);
polf (3, right_DE_left3); 
	color (silver9);
polf (3, right_DE_bottom); 
	color (silver8);
polf (3, right_DE_right5); 
	color (silver5);
polf (3, right_DE_left2); 
	color (silver7);
polf (3, right_DE_right4); 
	color (silver4);
polf (3, right_DE_left1); 
	color (silver6);
polf (3, right_DE_right3); 
	color (silver3);
polf (3, right_DE_top); 
	color (silver5);
polf (3, right_DE_right2); 
	color (silver4);
polf (3, right_DE_right1); 
	color (silver3);
polf (4, right_stab_mid); 
polf (11, right_outer_wing_top); 
	color (silver6);
polf (7, right_ltail); 
	color (red);
RIGHT_WING_TIP;
	color (silver6);
polf (9, right_utail); 
	color (silver3);
polf (12, right_stab_tip); 
closeobj();


makeobj(obj++);
color(silver6);
polf(10,far_away_wings);
polf(6,far_away_stab);
polf(10,far_away_left_side);
polf(10,far_away_right_side);
polf(6,far_away_left_tail);
polf(6,far_away_right_tail);
polf(10,far_away_left_boom);
polf(10,far_away_right_boom);
polf(12,far_away_fus);
color(white);
LEFT_WING_TIP;
color(red);
RIGHT_WING_TIP;
closeobj();

    makeobj (obj++);		/* shadow	*/
	color (black);
	setpattern(3);
polf(10,far_away_wings);
polf(6,far_away_stab);
polf(10,far_away_left_side);
polf(10,far_away_right_side);
polf(6,far_away_left_tail);
polf(6,far_away_right_tail);
polf(10,far_away_left_boom);
polf(10,far_away_right_boom);
polf(12,far_away_fus);
	setpattern(0);
    closeobj ();

    makeobj (obj+100);		/* shadow far away	*/
	color (black);
	setpattern(3);
polf(10,far_away_wings);
polf(6,far_away_stab);
polf(10,far_away_left_side);
polf(10,far_away_right_side);
polf(6,far_away_left_tail);
polf(6,far_away_right_tail);
polf(10,far_away_left_boom);
polf(10,far_away_right_boom);
polf(12,far_away_fus);
	setpattern(0);
    closeobj ();
}
