#!/usr/bin/env python


import os


output = open("index.html", "w")

output.write('<HTML><TITLE>Thumbnails</TITLE>\n')
output.write('<BODY BGCOLOR="#ffffff" MARGINWIDTH=72 '
    'LEFTMARGIN=72 RIGHTMARGIN=72><BR><BR><BR>\n');

lines = open("INDEX").readlines()

for line in lines:
    filename = line[0:8]
    description = line[8:]

    fixed_filename = filename[:-4] + "-fixed.jpg"

    output.write(
        '<A HREF="../../alicepics/%s"><IMG SRC="%s"></A><TT>&nbsp;&nbsp;&nbsp;%s&nbsp;&nbsp;&nbsp;</TT>' %
            (filename, filename, filename));
    if not os.path.exists(filename):
        os.system("MAKE_THUMBNAIL " + filename)

    if os.path.exists("../../alicepics/" + fixed_filename):
        output.write(
            '<A HREF="../../alicepics/%s"><IMG SRC="%s"></A><TT>&nbsp;&nbsp;&nbsp;%s&nbsp;&nbsp;&nbsp;</TT>' %
                (fixed_filename, fixed_filename, fixed_filename));
        if not os.path.exists(fixed_filename):
            os.system("MAKE_THUMBNAIL " + fixed_filename)

    output.write(
        '%s<p>' %
        (description));


output.write('</BODY></HTML>\n')

