
// Reads a hex file from stdin and generates an asm file on stdout.
// The symbols for the binary and the count are specified on the
// command line.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../emulator/readhex.h"

int main(int argc, char *argv[]) {
    if (argc != 4) {
        fprintf(stderr, "Usage: hex2asm BIN_SYMBOL COUNT_SYMBOL START\n");
        return 1;
    }
    char *bin_symbol = argv[1];
    char *count_symbol = argv[2];
    long start_address = strtol(argv[3], NULL, 0);

    // Read hex file.
    struct memory_desc md;
    unsigned char buffer[1024*64];
    memset(buffer, '\0', sizeof(buffer));
    memory_desc_init(&md, buffer, start_address, sizeof(buffer));
    int success = read_hex(stdin, memory_desc_store, &md, 1);
    if (!success) {
        fprintf(stderr, "hex2asm: Failed to read the input hex file\n");
        return 1;
    }

    // Determine size of buffer.
    int size = md.size_written;
    fprintf(stderr, "hex2asm: Hex file has %d bytes\n", size);

    // Write asm file.
    printf("; This file was automatically generated by hex2asm. Do not modify.\n\n");
    for (int i = 0; i < size; i++) {
        if (i % 16 == 0) {
            if (i == 0) {
                printf("%s:", bin_symbol);
            } else {
                printf("\n");
            }
            printf("\tdefb\t");
        } else {
            printf(", ");
        }
        printf("%03XH", buffer[i]);
    }
    printf("\n%s:\tdefw\t%d\n", count_symbol, size);

    return 0;
}

