all: alice4view alice4save

alice4view: alice4view.cpp
	g++ -O2 -g -Wall alice4view.cpp -L/opt/local/lib -I/opt/local/include/ -lfreeimageplus -lfreeimage -o alice4view

alice4save: alice4save.cpp
	g++ -O2 -g -Wall alice4save.cpp -L/opt/local/lib -I/opt/local/include/ -lfreeimageplus -lfreeimage -o alice4save
