#!/bin/bash

ASM=../brads_alice2_archive/asm

# true/false to easily enable to modification of zcc_out.asm.
if true; then
    echo "Building az80"
    (cd $ASM/az80 && make) || exit 1

    echo "--------------------------------------------------------------------------------"
    echo "Building zcc"
    (cd ../zcc && make) || exit 1

    echo "--------------------------------------------------------------------------------"
    echo "Building blan9"
    make || exit 1
    cp zcc_out.s $ASM/zcc_out.asm
fi

echo "--------------------------------------------------------------------------------"
echo "Assembling ROM"
(cd $ASM && ./asm80 rom.asm) || exit 1

echo "--------------------------------------------------------------------------------"
echo "Running emulator"
(cd ../emulator && make && ./emulator $ASM/rom.hex) || exit 1


